### PR TITLE
update readme and fix tests

### PR DESCRIPTION
**Pull request by clifton**
get these errors on the test suite:

```
hypothesis.errors.FailedHealthCheck: tests/test_invariants.py::test_cannot_make_instant_profit_around_rebalance uses the 'vault' 
fixture, which is reset between function calls but not between test cases generated by `@given(...)`.  You can change it to a 
module- or session-scoped fixture if it is safe to reuse; if not we recommend using a context manager inside your test function. 
 See https://docs.pytest.org/en/latest/how-to/fixtures.html#scope-sharing-fixtures-across-classes-modules-packages-or-session 
for details on fixture scope.

E                               See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you
 want to disable just this health check, add HealthCheck.function_scoped_fixture to the suppress_health_check settings for this test.

../../../.local/lib/python3.8/site-packages/hypothesis/extra/pytestplugin.py:199: FailedHealthCheck
============================================================== short test summary info ===============================================================
FAILED tests/test_invariants.py::test_rebalance_invariants - hypothesis.errors.FailedHealthCheck: tests/test_invariants.py::test_rebalance_invarian...
FAILED tests/test_invariants.py::test_cannot_make_instant_profit_from_deposit_then_withdraw - hypothesis.errors.FailedHealthCheck: tests/test_invar...
FAILED tests/test_invariants.py::test_cannot_make_instant_profit_from_manipulated_deposit - hypothesis.errors.FailedHealthCheck: tests/test_invaria...
FAILED tests/test_invariants.py::test_cannot_make_instant_profit_from_manipulated_withdraw - hypothesis.errors.FailedHealthCheck: tests/test_invari...
FAILED tests/test_invariants.py::test_cannot_make_instant_profit_around_rebalance - hypothesis.errors.FailedHealthCheck: tests/test_invariants.py::...
============================================================ 5 failed, 1 passed in 26.59s ============================================================
```

id also like to add github CI and package management to the project but ganache and poetry don't seem to like each other (can't pass compiler flags to poetry)

### CODE REVIEW

**Comment by clifton** [comment]
> hypothesis.errors.FailedHealthCheck: tests/test_invariants.py::test_withdraw_invariants uses the 'vault' fixture, which is reset between function calls but not between test cases generated by `@given(...)`. You can change it to a module- or session-scoped fixture if it is safe to reuse; if not we recommend using a context manager inside your test function. See https://docs.pytest.org/en/latest/how-to/fixtures.html#scope-sharing-fixtures-across-classes-modules-packages-or-session for details on fixture scope.
See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.function_scoped_fixture to the suppress_health_check settings for this test.

```
../../../.local/lib/python3.8/site-packages/hypothesis/extra/pytestplugin.py:199: FailedHealthCheck
== short test summary info ====
FAILED tests/test_invariants.py::test_withdraw_invariants - hypothesis.errors.FailedHealthCheck: tests/test_invariant...
=== 1 failed, 45 passed in 477.60s (0:07:57) ===
```

**Comment by clifton** [comment]
also tried swapping to poetry for robustness, but its kind-of a mess with ganache

**Comment by mxwtnb** [comment]
hey clifton, thx for the PR and sorry for being slow to get back on this

was wondering if you're still seeing these tests fail?

**Comment by mxwtnb** [comment]
ah actually i just tried it on a different machine and get the same error now - i'm guessing it's because of a different version of hypothesis

i think vault/strategy/pool are fixtures that should be reset between each run, though i'm not sure yet how to do this

> if not we recommend using a context manager inside your test function
do you happen to know how to implement this suggestion from the error message?

**Comment by clifton** [comment]
```diff
@@ -90,10 +90,14 @@ def vault(AlphaVault, AlphaStrategy, pool, router, tokens, gov, users, keeper):
     # limitThreshold = 1200
     # maxTwapDeviation = 200000 (just a big number)
     # twapDuration = 600 (10 minutes)
-    strategy = gov.deploy(AlphaStrategy, vault, 2400, 1200, 200000, 600, keeper)
+    strategy = gov.deploy(AlphaStrategy, vault, 2400,
+                          1200, 200000, 600, keeper)
     vault.setStrategy(strategy, {"from": gov})

+    start = chain.height
     yield vault
+    if chain.height > start:
+        chain.undo(chain.height - start)
```

something like that would probably fix the underlying problem with fixture re-use (assuming it is only the vault being reused) but does not stop the hypothesis errors. 🤷  perhaps this patch in conjunction with ignoring the errors?

**Comment by mxwtnb** [comment]
think below should fix it now - added a function that creates the vault/pool/strategy at the start of each run

https://github.com/charmfinance/alpha-vaults-contracts/commit/42b15d3c6d93b25f4ec1d69e01554fcf49c4ed20#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128R169

**Comment by clifton** [comment]
Yeah, that's the better solution. I'll close this pr

**Pull request closed without merging**
